abstract: converts numbers into Hungarian language text form.
author: 'Bálint Szilakszi <szbalint@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Lingua-HU-Numbers
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  perl: 5.6.0
version: 0.04
